clipped_std: false
custom_softmax: false
env:
  B: 5
  D: 1
  L0_pen: 0
  M: 10
  P: 5
  Q: 0
  Z: 100
  alpha: 0.1
  beta: 1
  challenging_concentrations: false
  illeg_act_handling: prop
  max_pen_violations: 999
  maxflow: 500
  product_cost: 1
  reg: 0
  reg_lambda: 1
  shrink_data: false
  uniform_data: false
id: 16
model:
  act_fn: ReLU
  arch_layersize: 128
  arch_n: 4
  batch_size: 64
  clip_range: 0.1
  ent_coef: 0.0001
  log_std_init: -2
  lr: 0.005
  lr_end: 0
  lr_sched: false
  use_sde: true
obs_normalizer: false
optimizer: PPO
policytype: MLP
reward_normalizer: true
starting_point: null
