clipped_std: false
custom_softmax: false
env:
  B: 5
  D: 1
  M: 10
  P: 5
  Q: 0
  Z: 100
  alpha: 0.1
  beta: 1
  illegal_flow_hndl: prop
  max_pen_violations: 999
  maxflow: 500
  product_cost: 0
  reg: 0
  reg_lambda: 1
  uniform_data: false
id: 19
model:
  act_fn: ReLU
  arch_layersize: 128
  arch_n: 4
  batch_size: 64
  clip_range: 0.1
  ent_coef: 0.0001
  log_std_init: -2
  lr: 0.005
  lr_end: 0
  lr_sched: false
  use_sde: false
obs_normalizer: false
optimizer: TD3
policytype: MLP
reward_normalizer: true
starting_point: null
