clipped_std: true
custom_softmax: false
env:
  B: 0
  D: 1
  M: 10
  P: 0
  Q: 0
  Z: 100
  alpha: 0.1
  beta: 0
  maxflow: 50
  product_cost: 0
id: 4
model:
  act_fn: ReLU
  arch_layersize: 128
  arch_n: 4
  clip_range: 0.1
  ent_coef: 0.0001
  log_std_init: -2
  lr: 0.005
obs_normalizer: false
optimizer: PPO
policytype: MLP
reward_normalizer: true
starting_point: null
