defaults:
  seed: 0
  train_cfgs:
    device: cpu
    torch_threads: 16
    vector_env_nums: 1
    parallel: 1
    total_steps: 10000000
  algo_cfgs:
    steps_per_epoch: 20000
    update_iters: 10
    batch_size: 128
    target_kl: 0.01
    entropy_coef: 0.0
    reward_normalize: False
    cost_normalize: False
    obs_normalize: True
    kl_early_stop: False
    use_max_grad_norm: True
    max_grad_norm: 40.0
    use_critic_norm: True
    critic_norm_coef: 0.001
    gamma: 0.99
    cost_gamma: 0.99
    lam: 0.95
    lam_c: 0.95
    adv_estimation_method: gae
    standardized_rew_adv: True
    standardized_cost_adv: True
    penalty_coef: 0.0
    use_cost: True
    cg_damping: 0.1
    cg_iters: 15
    fvp_obs: None
    cost_limit: 25
    fvp_sample_freq: 1
  logger_cfgs:
    use_wandb: False
    wandb_project: omnisafe
    use_tensorboard: True
    save_model_freq: 100
    log_dir: "./runs"
    window_lens: 100
  model_cfgs:
    weight_initialization_mode: "kaiming_uniform"
    actor_type: gaussian_learning
    linear_lr_decay: True
    exploration_noise_anneal: False
    std_range: [0.5, 0.1]
    actor:
      hidden_sizes: [64, 64]
      activation: tanh
      lr: ~
    critic:
      hidden_sizes: [64, 64]
      activation: tanh
      lr: 0.001
